"""Line-art icon slugs for the guest ingredients list."""

CATEGORY_ICONS = {
    "Spirit": "bottle",
    "Mixer": "mixer",
    "Garnish": "garnish",
    "Other": "other",
}

# Exact names as stored in the ingredients table.
ICON_BY_NAME = {
    "151-proof rum": "rum",
    "Absinthe": "absinthe",
    "Agave syrup": "tequila",
    "Amaretto": "nut",
    "Amaro Nonino": "bitters",
    "Amontillado sherry": "wine",
    "Angostura bitters": "bitters",
    "Aperol": "orange",
    "Apple juice": "apple",
    "Apple liqueur": "apple",
    "Apricot brandy": "peach",
    "Asian pear": "pear",
    "Avocado": "avocado",
    "Baileys Irish Cream": "cream",
    "Banana liqueur": "banana",
    "Banana-infused rum": "banana",
    "Black pepper": "pepper",
    "Black raspberry liqueur": "berry",
    "Bourbon": "whiskey",
    "Brandy": "brandy",
    "Brown sugar": "sugar",
    "Butter": "butter",
    "Bénédictine": "herbal",
    "Campari": "bitters",
    "Cane syrup": "syrup",
    "Caramel syrup": "syrup",
    "Celery salt": "salt",
    "Celery stalk": "celery",
    "Champagne": "sparkling",
    "Champagne vinegar": "vinegar",
    "Cherry bitters": "bitters",
    "Cherry brandy": "cherry",
    "Chocolate": "chocolate",
    "Chocolate syrup": "chocolate",
    "Chocolate-infused vodka": "chocolate",
    "Cinnamon schnapps": "cinnamon",
    "Cinnamon stick": "cinnamon",
    "Cinnamon syrup": "cinnamon",
    "Clamato": "tomato",
    "Cloves": "clove",
    "Club soda": "soda",
    "Coconut cream": "coconut",
    "Coconut rum": "coconut",
    "Coffee": "coffee",
    "Cognac": "brandy",
    "Cointreau": "orange",
    "Cola": "soda",
    "Cranberry juice": "berry",
    "Crème de violette": "floral",
    "Cucumber": "cucumber",
    "Cynar": "herbal",
    "Dark crème de cacao": "chocolate",
    "Dark rum": "rum",
    "Dry vermouth": "vermouth",
    "Egg white": "egg",
    "Espresso": "coffee",
    "Falernum": "rum",
    "Frangelico": "nut",
    "Fresh pineapple": "pineapple",
    "Gin": "gin",
    "Ginger ale": "ginger",
    "Ginger beer": "ginger",
    "Gold rum": "rum",
    "Grand Marnier": "orange",
    "Grapefruit juice": "grapefruit",
    "Grated chocolate": "chocolate",
    "Green Chartreuse": "herbal",
    "Green crème de menthe": "mint",
    "Green olives": "olive",
    "Grenadine": "berry",
    "Guinness Stout": "beer",
    "Habanero vodka": "chili",
    "Heavy cream": "cream",
    "Honey": "honey",
    "Honey syrup": "honey",
    "Hot chocolate": "chocolate",
    "Hot sauce": "chili",
    "Ice": "ice",
    "Irish whiskey": "whiskey",
    "Kahlua": "coffee",
    "Key lime juice": "lime",
    "Lemon": "lemon",
    "Lemon juice": "lemon",
    "Lemonade": "lemon",
    "Licor 43": "bottle",
    "Lime": "lime",
    "Lime juice": "lime",
    "Limoncello": "lemon",
    "Madeira": "wine",
    "Mango juice": "mango",
    "Maraschino cherry": "cherry",
    "Maraschino liqueur": "cherry",
    "Mezcal": "mezcal",
    "Midori": "melon",
    "Milk": "milk",
    "Mint leaves": "mint",
    "Nutmeg": "nutmeg",
    "Olive brine": "olive",
    "Orange": "orange",
    "Orange blossom water": "floral",
    "Orange curaçao": "orange",
    "Orange juice": "orange",
    "Orange marmalade": "orange",
    "Ouzo": "anise",
    "Passion fruit juice": "passionfruit",
    "Passion fruit syrup": "passionfruit",
    "Passionfruit purée": "passionfruit",
    "Peach brandy": "peach",
    "Peach liqueur": "peach",
    "Peach purée": "peach",
    "Peach schnapps": "peach",
    "Peach slice": "peach",
    "Pear liqueur": "pear",
    "Pear slice": "pear",
    "Peychaud's bitters": "bitters",
    "Pimm's No. 1": "pimms",
    "Pineapple juice": "pineapple",
    "Pineapple rum": "pineapple",
    "Pink grapefruit juice": "grapefruit",
    "Prosecco": "sparkling",
    "Raisins": "raisin",
    "Raspberry syrup": "berry",
    "Red wine": "wine",
    "Rosemary": "rosemary",
    "Rye whiskey": "whiskey",
    "Sake": "sake",
    "Salt": "salt",
    "Scotch": "whiskey",
    "Simple syrup": "syrup",
    "Sloe gin": "berry",
    "Southern Comfort": "whiskey",
    "Spiced rum": "rum",
    "St-Germain": "floral",
    "Strawberry": "strawberry",
    "Strawberry syrup": "strawberry",
    "Sugar": "sugar",
    "Sugar cube": "sugar",
    "Sweet vermouth": "vermouth",
    "Tea": "tea",
    "Tequila": "tequila",
    "Tonic water": "soda",
    "Triple sec": "orange",
    "Vanilla ice cream": "ice-cream",
    "Vodka": "vodka",
    "Water": "water",
    "Whipped cream": "cream",
    "White crème de cacao": "chocolate",
    "White crème de menthe": "mint",
    "White peach purée": "peach",
    "White rum": "rum",
    "Worcestershire sauce": "sauce",
}

_KEYWORD_ICONS = (
    ("rum", "rum"),
    ("whiskey", "whiskey"),
    ("bourbon", "whiskey"),
    ("scotch", "whiskey"),
    ("vodka", "vodka"),
    ("gin", "gin"),
    ("tequila", "tequila"),
    ("mezcal", "mezcal"),
    ("brandy", "brandy"),
    ("cognac", "brandy"),
    ("vermouth", "vermouth"),
    ("bitters", "bitters"),
    ("syrup", "syrup"),
    ("juice", "mixer"),
    ("soda", "soda"),
    ("wine", "wine"),
    ("champagne", "sparkling"),
    ("prosecco", "sparkling"),
    ("mint", "mint"),
    ("coffee", "coffee"),
    ("cream", "cream"),
    ("lime", "lime"),
    ("lemon", "lemon"),
    ("orange", "orange"),
    ("cherry", "cherry"),
)


def category_slug(category):
    return (category or "other").strip().lower().replace(" ", "-") or "other"


def icon_for_ingredient(name, category="Other"):
    if name in ICON_BY_NAME:
        return ICON_BY_NAME[name]
    key = (name or "").strip().lower()
    for needle, slug in _KEYWORD_ICONS:
        if needle in key:
            return slug
    return CATEGORY_ICONS.get(category, "other")
