"""Party themes: families, slugs, and recipe membership.

A drink may sit in several themes. Assignments are bartender judgment, not
exclusive tags — overlap (spritz on Italian night and Sparkling) is intended.
"""

FEATURED_THEME_SLUG = "featured"

THEME_FAMILIES = (
    {
        "key": "dinner",
        "name": "Dinner / cuisine",
        "blurb": "Match the bottle to the table.",
    },
    {
        "key": "structure",
        "name": "Structure / family",
        "blurb": "How the drink is built.",
    },
    {
        "key": "flavor",
        "name": "Flavor / mood",
        "blurb": "What it tastes like in the glass.",
    },
    {
        "key": "when",
        "name": "When / how",
        "blurb": "Season, hour, and effort.",
    },
)

THEMES = (
    # Dinner / cuisine
    ("mexican-agave", "Mexican / Agave", "dinner", "Tequila, mezcal, lime, chili — Paloma and Margarita night.", 10),
    ("italian-aperitivo", "Italian Aperitivo", "dinner", "Spritz, Negroni, vermouth, bitter and bubbles.", 20),
    ("mediterranean", "Mediterranean", "dinner", "Herbal, citrus, olive — mezze and couscous-night drinks.", 30),
    ("asian-spice", "Asian Spice", "dinner", "Ginger, lime, heat-contrast for curry and stir-fry nights.", 40),
    ("latin-american", "Latin American", "dinner", "Rum, agave, and bright citrus for Peruvian, Argentine, or grill nights.", 50),
    ("american-comfort", "American Comfort", "dinner", "Whiskey, sours, and highballs with burgers, pot pie, steak.", 60),
    # Structure / family
    ("classics", "Classics", "structure", "IBA templates and drinks that earned their keep.", 10),
    ("tiki-tropical", "Tiki / Tropical", "structure", "Rum, pineapple, orgeat energy, over-the-top garnish.", 20),
    ("sours", "Sours", "structure", "Spirit, citrus, and sugar — the template that never dies.", 30),
    ("spirit-forward", "Spirit-Forward", "structure", "Stirred, short, and boozy.", 40),
    ("highball", "Highball", "structure", "Long, built, fizzy or lengthened.", 50),
    ("sparkling", "Sparkling", "structure", "Champagne and prosecco builds.", 60),
    # Flavor / mood
    ("garden-herbal", "Garden / Herbal", "flavor", "Gin, cucumber, basil, mint, floral.", 10),
    ("spicy-smoky", "Spicy & Smoky", "flavor", "Chili, mezcal smoke, cinnamon heat.", 20),
    ("coffee-dessert", "Coffee & Dessert", "flavor", "Espresso, chocolate, cream, after-dinner.", 30),
    ("bright-citrus", "Bright Citrus", "flavor", "Lemon, lime, grapefruit-forward without being a full sour set.", 40),
    ("bitter", "Bitter", "flavor", "Campari, amari, aperitivo-leaning.", 50),
    ("jazzy", "Jazzy", "flavor", "Speakeasy and jazz-club drinks — stirred whiskey, gin, vermouth, and a little sparkle.", 60),
    # When / how
    ("summer-fresh", "Summer Fresh", "when", "Patio, pool, and porch weather.", 10),
    ("autumn-spice", "Autumn Spice", "when", "Leaves down, bitters and baking spice up.", 20),
    ("winter-warm", "Winter Warm", "when", "Hot mugs, stirred whiskey, dessert drinks.", 30),
    ("brunch", "Brunch", "when", "Late morning through early afternoon.", 40),
    ("easy", "Easy", "when", "Few ingredients, weeknight, no theater.", 50),
    ("batch-punch", "Batch / Punch", "when", "Pitcher, punch bowl, or scale-up friendly.", 60),
    ("low-abv", "Low-ABV", "when", "Sessionable — spritzes, sodas, and lighter builds.", 70),
)

# Dark bases, one distinctive highlight each. Keys match CSS variables (minus --).
THEME_PALETTES = {
    "mexican-agave": {
        "bg": "#0e120e",
        "bg-elevated": "#162016",
        "bg-card": "#1c281c",
        "text": "#f2f4e8",
        "muted": "#8fa080",
        "accent": "#d6e25a",
        "accent-dim": "#9aab38",
        "border": "#2c3c28",
        "theme-glow": "#1a3a22",
    },
    "italian-aperitivo": {
        "bg": "#140c0e",
        "bg-elevated": "#221014",
        "bg-card": "#2a161a",
        "text": "#f8ece8",
        "muted": "#b08888",
        "accent": "#ff6b42",
        "accent-dim": "#d44a30",
        "border": "#4a2428",
        "theme-glow": "#3a1218",
    },
    "mediterranean": {
        "bg": "#10140e",
        "bg-elevated": "#1a2216",
        "bg-card": "#222a1c",
        "text": "#eef2e4",
        "muted": "#8a9878",
        "accent": "#c4c86a",
        "accent-dim": "#8e9448",
        "border": "#343c28",
        "theme-glow": "#243018",
    },
    "asian-spice": {
        "bg": "#140e0a",
        "bg-elevated": "#24180e",
        "bg-card": "#2c1e12",
        "text": "#f6eee4",
        "muted": "#b09070",
        "accent": "#f0b43c",
        "accent-dim": "#c87820",
        "border": "#443018",
        "theme-glow": "#3a1808",
    },
    "latin-american": {
        "bg": "#120c10",
        "bg-elevated": "#22141c",
        "bg-card": "#2a1824",
        "text": "#f8e8f0",
        "muted": "#b08098",
        "accent": "#f04a78",
        "accent-dim": "#c03058",
        "border": "#4a2438",
        "theme-glow": "#2a1020",
    },
    "american-comfort": {
        "bg": "#120e0a",
        "bg-elevated": "#1e1810",
        "bg-card": "#261e14",
        "text": "#f4eadc",
        "muted": "#a09078",
        "accent": "#d4923c",
        "accent-dim": "#a86c28",
        "border": "#3c3020",
        "theme-glow": "#2a1c10",
    },
    "classics": {
        "bg": "#0e1218",
        "bg-elevated": "#181e28",
        "bg-card": "#1e2632",
        "text": "#eef2f6",
        "muted": "#8a98a8",
        "accent": "#d4c8a8",
        "accent-dim": "#a89878",
        "border": "#323c48",
        "theme-glow": "#1a2438",
    },
    "tiki-tropical": {
        "bg": "#081218",
        "bg-elevated": "#0e2230",
        "bg-card": "#122a38",
        "text": "#e8f6f4",
        "muted": "#78a8a8",
        "accent": "#ffc933",
        "accent-dim": "#d49a18",
        "border": "#1e4450",
        "theme-glow": "#083040",
    },
    "sours": {
        "bg": "#12140c",
        "bg-elevated": "#1e2210",
        "bg-card": "#262a14",
        "text": "#f6f6e4",
        "muted": "#a8a870",
        "accent": "#f5e14a",
        "accent-dim": "#c4b020",
        "border": "#3c4020",
        "theme-glow": "#2a2a0c",
    },
    "spirit-forward": {
        "bg": "#100c0a",
        "bg-elevated": "#1c1410",
        "bg-card": "#241a14",
        "text": "#f4e8dc",
        "muted": "#a08070",
        "accent": "#c46a38",
        "accent-dim": "#9a4e28",
        "border": "#3c2820",
        "theme-glow": "#241008",
    },
    "highball": {
        "bg": "#0a1218",
        "bg-elevated": "#12202a",
        "bg-card": "#162830",
        "text": "#e8f4f8",
        "muted": "#78a0b0",
        "accent": "#6ec8e8",
        "accent-dim": "#3e98b8",
        "border": "#204050",
        "theme-glow": "#0c2838",
    },
    "sparkling": {
        "bg": "#141018",
        "bg-elevated": "#201828",
        "bg-card": "#2a1e32",
        "text": "#f8f0f4",
        "muted": "#b098a8",
        "accent": "#f0d8a8",
        "accent-dim": "#c8a878",
        "border": "#403048",
        "theme-glow": "#2a1828",
    },
    "garden-herbal": {
        "bg": "#0c1410",
        "bg-elevated": "#14201a",
        "bg-card": "#1a2a20",
        "text": "#e8f4ea",
        "muted": "#7aa888",
        "accent": "#6ec87a",
        "accent-dim": "#3e9a52",
        "border": "#284830",
        "theme-glow": "#143020",
    },
    "spicy-smoky": {
        "bg": "#0e0a0a",
        "bg-elevated": "#1c1010",
        "bg-card": "#261414",
        "text": "#f8ece8",
        "muted": "#a88880",
        "accent": "#ff5a2a",
        "accent-dim": "#c84018",
        "border": "#442018",
        "theme-glow": "#2a1008",
    },
    "coffee-dessert": {
        "bg": "#0e0a08",
        "bg-elevated": "#1a1410",
        "bg-card": "#221a14",
        "text": "#f4ece4",
        "muted": "#a09080",
        "accent": "#c48848",
        "accent-dim": "#9a6838",
        "border": "#3c2c20",
        "theme-glow": "#241810",
    },
    "bright-citrus": {
        "bg": "#14100c",
        "bg-elevated": "#241810",
        "bg-card": "#2c1e14",
        "text": "#f8f0e8",
        "muted": "#b89880",
        "accent": "#ff7a5c",
        "accent-dim": "#d45038",
        "border": "#4a3024",
        "theme-glow": "#2e1810",
    },
    "bitter": {
        "bg": "#12080c",
        "bg-elevated": "#201014",
        "bg-card": "#2a141a",
        "text": "#f8e8ec",
        "muted": "#b07888",
        "accent": "#e02040",
        "accent-dim": "#b01830",
        "border": "#4a1828",
        "theme-glow": "#2a0810",
    },
    "jazzy": {
        "bg": "#10080c",
        "bg-elevated": "#1c1014",
        "bg-card": "#261418",
        "text": "#f6ead8",
        "muted": "#b09080",
        "accent": "#d4a84a",
        "accent-dim": "#a87828",
        "border": "#4a2830",
        "theme-glow": "#3a1018",
    },
    "summer-fresh": {
        "bg": "#0a1614",
        "bg-elevated": "#102420",
        "bg-card": "#142c28",
        "text": "#e8f8f4",
        "muted": "#78b0a8",
        "accent": "#4ad4c4",
        "accent-dim": "#2aa898",
        "border": "#1c4844",
        "theme-glow": "#0c302c",
    },
    "autumn-spice": {
        "bg": "#120e0a",
        "bg-elevated": "#22180e",
        "bg-card": "#2a1c12",
        "text": "#f6eadc",
        "muted": "#b08868",
        "accent": "#e07030",
        "accent-dim": "#b05020",
        "border": "#4a2c18",
        "theme-glow": "#2a1408",
    },
    "winter-warm": {
        "bg": "#120c10",
        "bg-elevated": "#201418",
        "bg-card": "#2a181c",
        "text": "#f8ece8",
        "muted": "#b08888",
        "accent": "#e88850",
        "accent-dim": "#c06038",
        "border": "#4a2828",
        "theme-glow": "#2a1418",
    },
    "brunch": {
        "bg": "#14120e",
        "bg-elevated": "#221e16",
        "bg-card": "#2a241c",
        "text": "#f8f2e8",
        "muted": "#b0a088",
        "accent": "#f0c24a",
        "accent-dim": "#c89828",
        "border": "#443c24",
        "theme-glow": "#2a2418",
    },
    "easy": {
        "bg": "#0e141c",
        "bg-elevated": "#162028",
        "bg-card": "#1c2832",
        "text": "#e8f0f6",
        "muted": "#88a0b0",
        "accent": "#7ab0e0",
        "accent-dim": "#4a88c0",
        "border": "#283848",
        "theme-glow": "#142030",
    },
    "batch-punch": {
        "bg": "#140c10",
        "bg-elevated": "#24141a",
        "bg-card": "#2e1820",
        "text": "#f8e8ee",
        "muted": "#b08090",
        "accent": "#e84868",
        "accent-dim": "#c03048",
        "border": "#4a2030",
        "theme-glow": "#2e1018",
    },
    "low-abv": {
        "bg": "#101018",
        "bg-elevated": "#1a1828",
        "bg-card": "#221e32",
        "text": "#f0ecf8",
        "muted": "#9888b0",
        "accent": "#b8a0e0",
        "accent-dim": "#8870c0",
        "border": "#383048",
        "theme-glow": "#181428",
    },
    "featured": {
        "bg": "#161208",
        "bg-elevated": "#241c0c",
        "bg-card": "#2c2410",
        "text": "#fff6e0",
        "muted": "#b8a06a",
        "accent": "#ffd45a",
        "accent-dim": "#d4a828",
        "border": "#4a3c14",
        "theme-glow": "#3a2c08",
    },
}


def palette_style(slug):
    """Inline CSS custom properties for a theme slug, or empty."""
    pal = THEME_PALETTES.get(slug or "")
    if not pal:
        return ""
    return ";".join(f"--{key}: {value}" for key, value in pal.items())


# Curated ticker lines per theme. Attribution uses the same "movie" field as the TV ticker.
# Mix: movie, sports, celebrity, and historic — humorous, ironic, or actually useful.
THEME_QUOTES = {
    "mexican-agave": [
        ("Para todo mal, mezcal; para todo bien, también.", "Oaxacan proverb"),
        ("Badges? We ain't got no badges. We don't need no badges.", "The Treasure of the Sierra Madre"),
        ("Say my name.", "Breaking Bad"),
        ("I am the one who knocks.", "Breaking Bad"),
        ("Wastin' away again in Margaritaville.", "Jimmy Buffett"),
        ("It's five o'clock somewhere.", "Alan Jackson & Jimmy Buffett"),
        ("Everybody has a plan until they get punched in the mouth.", "Mike Tyson"),
        ("If you can't stand the heat, get out of the kitchen.", "Harry S. Truman"),
        ("Your body is not a temple, it's an amusement park. Enjoy the ride.", "Anthony Bourdain"),
    ],
    "italian-aperitivo": [
        ("Leave the gun. Take the cannoli.", "The Godfather"),
        ("I'm going to make him an offer he can't refuse.", "The Godfather"),
        ("Life is a combination of magic and pasta.", "Federico Fellini"),
        ("Everything you see I owe to spaghetti.", "Sophia Loren"),
        ("When in Rome, do as the Romans do.", "St. Ambrose"),
        ("Tutti a tavola a mangiare.", "Lidia Bastianich"),
        ("I cook with wine. Sometimes I even add it to the food.", "W. C. Fields"),
        ("Nice guys finish last.", "Leo Durocher"),
        ("You cannot be serious!", "John McEnroe"),
    ],
    "mediterranean": [
        ("In vino veritas.", "Pliny the Elder"),
        ("Eat, drink, and be merry, for tomorrow we die.", "Ecclesiastes / Isaiah"),
        ("Tell me what you eat, and I will tell you what you are.", "Jean Anthelme Brillat-Savarin"),
        ("Fish, to taste right, must swim three times: in water, in butter, and in wine.", "Auguste Escoffier"),
        ("There are two kinds of people: Greeks, and everyone else who wish they were Greek.", "My Big Fat Greek Wedding"),
        ("Paris is always a good idea.", "Audrey Hepburn"),
        ("Avoid fried meats which angry up the blood.", "Satchel Paige"),
        ("A day without sunshine is like, you know, night.", "Steve Martin"),
        ("If you obey all the rules, you miss all the fun.", "Katharine Hepburn"),
    ],
    "asian-spice": [
        ("For relaxing times, make it Suntory time.", "Lost in Translation"),
        ("Be water, my friend.", "Bruce Lee"),
        ("Wax on, wax off.", "The Karate Kid"),
        ("Do or do not. There is no try.", "The Empire Strikes Back"),
        ("Float like a butterfly, sting like a bee.", "Muhammad Ali"),
        ("Everybody has a plan until they get punched in the mouth.", "Mike Tyson"),
        ("I skate to where the puck is going to be, not where it has been.", "Wayne Gretzky"),
        ("First learn stand, then learn fly. Nature rule, Daniel-san, not mine.", "The Karate Kid"),
        ("The successful warrior is the average man, with laser-like focus.", "Bruce Lee"),
    ],
    "latin-american": [
        ("Why is the rum gone?", "Pirates of the Caribbean"),
        ("The code is more what you'd call guidelines than actual rules.", "Pirates of the Caribbean"),
        ("Savvy?", "Pirates of the Caribbean"),
        ("Say hello to my little friend!", "Scarface"),
        ("Nobody puts Baby in a corner.", "Dirty Dancing"),
        ("It ain't braggin' if you can back it up.", "Dizzy Dean"),
        ("Success is no accident.", "Pelé"),
        ("We use food as a weapon for peace.", "José Andrés"),
        ("I spent a lot of money on booze, birds and fast cars. The rest I just squandered.", "George Best"),
        ("Don't cry for me Argentina.", "Evita"),
    ],
    "american-comfort": [
        ("Too much of anything is bad, but too much good whiskey is barely enough.", "Mark Twain"),
        ("The only time to eat diet food is while you're waiting for the steak to cook.", "Julia Child"),
        ("If you're afraid of butter, use cream.", "Julia Child"),
        ("I drink your milkshake!", "There Will Be Blood"),
        ("That'll do, pig. That'll do.", "Babe"),
        ("You play to win the game!", "Herm Edwards"),
        ("Don't worry about the horse being blind, just load the wagon.", "John Madden"),
        ("I asked my caddie for a sand wedge and he came back with a ham on rye.", "Chi-Chi Rodríguez"),
        ("I want to keep fighting because it is the only thing that keeps me out of the hamburger joints.", "George Foreman"),
        ("Where's the beef?", "Clara Peller"),
    ],
    "classics": [
        ("Of all the gin joints in all the towns in all the world, she walks into mine.", "Casablanca"),
        ("Here's looking at you, kid.", "Casablanca"),
        ("A martini. Shaken, not stirred.", "Goldfinger"),
        ("I like to have a martini, two at the most. Three I'm under the table, four I'm under my host.", "Dorothy Parker"),
        ("The only American invention as perfect as a sonnet is the martini.", "H. L. Mencken"),
        ("Work is the curse of the drinking classes.", "Oscar Wilde"),
        ("I have the simplest tastes. I am always satisfied with the best.", "Oscar Wilde"),
        ("This is the way.", "The Mandalorian"),
        ("The future ain't what it used to be.", "Yogi Berra"),
        ("The older I get, the better I used to be.", "Lee Trevino"),
        ("Inconceivable!", "The Princess Bride"),
    ],
    "tiki-tropical": [
        ("Why is the rum gone?", "Pirates of the Caribbean"),
        ("We're gonna need a bigger boat.", "Jaws"),
        ("Just keep swimming.", "Finding Nemo"),
        ("I have made fire!", "Cast Away"),
        ("Wastin' away again in Margaritaville.", "Jimmy Buffett"),
        ("It's five o'clock somewhere.", "Alan Jackson & Jimmy Buffett"),
        ("If you don't know where you are going, you might wind up someplace else.", "Yogi Berra"),
        ("I'd rather be lucky than good.", "Lefty Gomez"),
        ("When we win, I eat a lot. When we lose, I eat a lot. When we're rained out, I eat a lot.", "Tommy Lasorda"),
        ("If you can't get to paradise, I'll bring it to you.", "Donn Beach"),
    ],
    "sours": [
        ("If life gives you lemons, find somebody whose life has given them vodka, and have a party.", "Ron White"),
        ("When life gives you lemons, make lemonade.", "Proverb"),
        ("Oops, I dropped the lemon tart.", "Massimo Bottura"),
        ("Salt, fat, acid, heat.", "Samin Nosrat"),
        ("You cannot be serious!", "John McEnroe"),
        ("I am serious. And don't call me Shirley.", "Airplane!"),
        ("The only difference between a good shot and a bad shot is if it goes in or not.", "Charles Barkley"),
        ("It's just a flesh wound.", "Monty Python and the Holy Grail"),
        ("These pretzels are making me thirsty.", "Seinfeld"),
    ],
    "spirit-forward": [
        ("A martini. Shaken, not stirred.", "Goldfinger"),
        ("Of all the gin joints in all the towns in all the world, she walks into mine.", "Casablanca"),
        ("The whole world is about three drinks behind.", "Humphrey Bogart"),
        ("You're not drunk if you can lie on the floor without holding on.", "Dean Martin"),
        ("Ninety percent I'll spend on whiskey, women, and the good life. The other ten I'll probably waste.", "Ken Stabler"),
        ("Too much of anything is bad, but too much good whiskey is barely enough.", "Mark Twain"),
        ("I demand to have some booze!", "Withnail and I"),
        ("We want the finest wines available to humanity, and we want them now!", "Withnail and I"),
        ("Do I feel lucky? Well, do ya, punk?", "Dirty Harry"),
        ("Don't look back. Something might be gaining on you.", "Satchel Paige"),
        ("I have taken more out of alcohol than alcohol has taken out of me.", "Winston Churchill"),
    ],
    "highball": [
        ("For relaxing times, make it Suntory time.", "Lost in Translation"),
        ("Just keep swimming.", "Finding Nemo"),
        ("Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", "Ferris Bueller's Day Off"),
        ("An escalator can never break. It can only become stairs.", "Mitch Hedberg"),
        ("I never drink water. Fish sleep in it.", "W. C. Fields"),
        ("Keep the juices flowing by jangling around gently as you move.", "Satchel Paige"),
        ("Beer is proof that God loves us and wants us to be happy.", "Benjamin Franklin"),
        ("Float like a butterfly, sting like a bee.", "Muhammad Ali"),
        ("Be water, my friend.", "Bruce Lee"),
    ],
    "sparkling": [
        ("Come quickly, I am tasting the stars!", "Dom Pérignon"),
        ("I only drink Champagne on two occasions, when I am in love and when I am not.", "Coco Chanel"),
        ("In victory, you deserve Champagne; in defeat, you need it.", "Napoleon Bonaparte"),
        ("I'm king of the world!", "Titanic"),
        ("To infinity and beyond!", "Toy Story"),
        ("Paris is always a good idea.", "Audrey Hepburn"),
        ("I can't wait until tomorrow, because I get better looking every day.", "Joe Namath"),
        ("I guarantee it.", "Joe Namath"),
        ("Can't repeat the past? Why of course you can!", "The Great Gatsby"),
        ("If you obey all the rules, you miss all the fun.", "Katharine Hepburn"),
    ],
    "garden-herbal": [
        ("I am Groot.", "Guardians of the Galaxy"),
        ("Anyone can cook.", "Ratatouille"),
        ("If you are what you eat, then I only want to eat the good stuff.", "Ratatouille"),
        ("You don't have to cook fancy or complicated masterpieces — just good food from fresh ingredients.", "Julia Child"),
        ("Wax on, wax off.", "The Karate Kid"),
        ("Better learn balance. Balance is key.", "The Karate Kid"),
        ("Be water, my friend.", "Bruce Lee"),
        ("Float like a butterfly, sting like a bee.", "Muhammad Ali"),
        ("A party without cake is just a meeting.", "Julia Child"),
    ],
    "spicy-smoky": [
        ("I love the smell of napalm in the morning.", "Apocalypse Now"),
        ("Everybody has a plan until they get punched in the mouth.", "Mike Tyson"),
        ("Float like a butterfly, sting like a bee.", "Muhammad Ali"),
        ("Here's Johnny!", "The Shining"),
        ("I am the one who knocks.", "Breaking Bad"),
        ("Why so serious?", "The Dark Knight"),
        ("Some men just want to watch the world burn.", "The Dark Knight"),
        ("If you can't stand the heat, get out of the kitchen.", "Harry S. Truman"),
        ("It ain't the heat, it's the humility.", "Yogi Berra"),
        ("Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.", "Terry Pratchett"),
    ],
    "coffee-dessert": [
        ("This is, excuse me, a damn fine cup of coffee.", "Twin Peaks"),
        ("I drink your milkshake!", "There Will Be Blood"),
        ("Life is like a box of chocolates.", "Forrest Gump"),
        ("Careful, man, there's a beverage here!", "The Big Lebowski"),
        ("The Dude abides.", "The Big Lebowski"),
        ("It's only a wafer-thin mint.", "Monty Python's The Meaning of Life"),
        ("Tea. Earl Grey. Hot.", "Star Trek: The Next Generation"),
        ("If you're afraid of butter, use cream.", "Julia Child"),
        ("A dessert without cheese is like a beautiful woman with only one eye.", "Jean Anthelme Brillat-Savarin"),
        ("When we win, I eat a lot. When we lose, I eat a lot.", "Tommy Lasorda"),
        ("Even bad coffee is better than no coffee at all.", "David Lynch"),
    ],
    "bright-citrus": [
        ("If life gives you lemons, find somebody whose life has given them vodka, and have a party.", "Ron White"),
        ("When life gives you lemons, make lemonade.", "Proverb"),
        ("Oops, I dropped the lemon tart.", "Massimo Bottura"),
        ("A day without sunshine is like, you know, night.", "Steve Martin"),
        ("These pretzels are making me thirsty.", "Seinfeld"),
        ("If you are caught on a golf course during a storm and are afraid of lightning, hold up a 1-iron. Not even God can hit a 1-iron.", "Lee Trevino"),
        ("The sun'll come out tomorrow.", "Annie"),
        ("I went to a restaurant that serves breakfast at any time. So I ordered French toast during the Renaissance.", "Steven Wright"),
        ("Salt, fat, acid, heat.", "Samin Nosrat"),
    ],
    "bitter": [
        ("Nice guys finish last.", "Leo Durocher"),
        ("Why so serious?", "The Dark Knight"),
        ("You either die a hero, or you live long enough to see yourself become the villain.", "The Dark Knight"),
        ("You cannot be serious!", "John McEnroe"),
        ("Playoffs? Don't talk about—playoffs?", "Jim Mora"),
        ("If you haven't got anything nice to say about anybody, come sit next to me.", "Dorothy Parker"),
        ("I've had a perfectly wonderful evening, but this wasn't it.", "Groucho Marx"),
        ("What we've got here is failure to communicate.", "Cool Hand Luke"),
        ("The reports of my death are greatly exaggerated.", "Mark Twain"),
        ("Hell is other people.", "Jean-Paul Sartre"),
    ],
    "summer-fresh": [
        ("Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", "Ferris Bueller's Day Off"),
        ("Just keep swimming.", "Finding Nemo"),
        ("We're gonna need a bigger boat.", "Jaws"),
        ("I feel the need—the need for speed.", "Top Gun"),
        ("The coldest winter I ever spent was a summer in San Francisco.", "Mark Twain"),
        ("If you obey all the rules, you miss all the fun.", "Katharine Hepburn"),
        ("There's no crying in baseball!", "A League of Their Own"),
        ("Nobody goes there anymore. It's too crowded.", "Yogi Berra"),
        ("It ain't the heat, it's the humility.", "Yogi Berra"),
        ("Avoid running at all times.", "Satchel Paige"),
        ("Carpe diem. Seize the day, boys.", "Dead Poets Society"),
    ],
    "autumn-spice": [
        ("Season of mists and mellow fruitfulness.", "John Keats"),
        ("Nothing gold can stay.", "Robert Frost"),
        ("The older I get, the better I used to be.", "Lee Trevino"),
        ("The future ain't what it used to be.", "Yogi Berra"),
        ("It gets late early out here.", "Yogi Berra"),
        ("Old age ain't no place for sissies.", "Bette Davis"),
        ("You know you're getting old when the candles cost more than the cake.", "Bob Hope"),
        ("There's no place like home.", "The Wizard of Oz"),
        ("I'm too old for this.", "Lethal Weapon"),
        ("I don't feel old. I don't feel anything until noon. Then it's time for my nap.", "Bob Hope"),
    ],
    "winter-warm": [
        ("Winter is coming.", "Game of Thrones"),
        ("Here's Johnny!", "The Shining"),
        ("Yippee-ki-yay.", "Die Hard"),
        ("Welcome to the party, pal.", "Die Hard"),
        ("The cold never bothered me anyway.", "Frozen"),
        ("I'll be back.", "The Terminator"),
        ("You shall not pass!", "The Lord of the Rings"),
        ("Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.", "Terry Pratchett"),
        ("Don't look back. Something might be gaining on you.", "Satchel Paige"),
        ("Go very light on the vices, such as carrying on in society. The social ramble ain't restful.", "Satchel Paige"),
    ],
    "brunch": [
        ("I'll have what she's having.", "When Harry Met Sally"),
        ("What about second breakfast?", "The Lord of the Rings"),
        ("I went to a restaurant that serves breakfast at any time. So I ordered French toast during the Renaissance.", "Steven Wright"),
        ("When we win, I eat a lot. When we lose, I eat a lot. When we're rained out, I eat a lot.", "Tommy Lasorda"),
        ("Avoid fried meats which angry up the blood.", "Satchel Paige"),
        ("I don't feel old. I don't feel anything until noon. Then it's time for my nap.", "Bob Hope"),
        ("The secret of staying young is to live honestly, eat slowly, and lie about your age.", "Lucille Ball"),
        ("Housework can't kill you, but why take a chance?", "Phyllis Diller"),
        ("A two-year-old is kind of like having a blender, but you don't have a top for it.", "Jerry Seinfeld"),
        ("Tea. Earl Grey. Hot.", "Star Trek: The Next Generation"),
        ("Nobody goes there anymore. It's too crowded.", "Yogi Berra"),
    ],
    "easy": [
        ("Store-bought is fine.", "Ina Garten"),
        ("How easy is that?", "Ina Garten"),
        ("Practice? We talkin' about practice?", "Allen Iverson"),
        ("I'm just here so I won't get fined.", "Marshawn Lynch"),
        ("I'd rather be lucky than good.", "Lefty Gomez"),
        ("Never put off till tomorrow what you can do the day after tomorrow just as well.", "Mark Twain"),
        ("I love deadlines. I love the whooshing noise they make as they go by.", "Douglas Adams"),
        ("An escalator can never break. It can only become stairs.", "Mitch Hedberg"),
        ("I don't need a timeout. I know what's going on. I just don't know what to do about it.", "Doug Moe"),
        ("The greatest dishes are very simple.", "Auguste Escoffier"),
        ("I am serious. And don't call me Shirley.", "Airplane!"),
        ("I intend to live forever. So far, so good.", "Steven Wright"),
    ],
    "batch-punch": [
        ("We're gonna need a bigger boat.", "Jaws"),
        ("I volunteer as tribute!", "The Hunger Games"),
        ("Welcome to the party, pal.", "Die Hard"),
        ("If you build it, he will come.", "Field of Dreams"),
        ("Pair up in threes.", "Yogi Berra"),
        ("We made too many wrong mistakes.", "Yogi Berra"),
        ("Don't worry about the horse being blind, just load the wagon.", "John Madden"),
        ("You miss 100 percent of the shots you don't take.", "Wayne Gretzky"),
        ("Talent wins games, but teamwork and intelligence win championships.", "Michael Jordan"),
        ("One for all, and all for one.", "The Three Musketeers"),
        ("The more the merrier.", "Proverb"),
    ],
    "low-abv": [
        ("Moderation is a fatal thing. Nothing succeeds like excess.", "Oscar Wilde"),
        ("I can resist everything except temptation.", "Oscar Wilde"),
        ("Everything in moderation, including moderation.", "Attributed to Oscar Wilde"),
        ("I used to be Snow White, but I drifted.", "Mae West"),
        ("Go very light on the vices, such as carrying on in society. The social ramble ain't restful.", "Satchel Paige"),
        ("I'm just here so I won't get fined.", "Marshawn Lynch"),
        ("I never drink water. Fish sleep in it.", "W. C. Fields"),
        ("I feel sorry for people who don't drink. When they wake up in the morning, that's as good as they're going to feel all day.", "Dean Martin"),
        ("Everybody's got to believe in something. I believe I'll have another drink.", "W. C. Fields"),
        ("Less is more.", "Robert Browning"),
        ("Tea. Earl Grey. Hot.", "Star Trek: The Next Generation"),
    ],
    "jazzy": [
        ("It don't mean a thing if it ain't got that swing.", "Duke Ellington"),
        ("If you have to ask what jazz is, you'll never know.", "Louis Armstrong"),
        ("Jazz is not dead, it just smells funny.", "Frank Zappa"),
        ("Play it, Sam. Play 'As Time Goes By.'", "Casablanca"),
        ("We'll always have Paris.", "Casablanca"),
        ("Do not fear mistakes. There are none.", "Miles Davis"),
        ("The piano ain't got no wrong notes.", "Thelonious Monk"),
        ("If you don't live it, it won't come out of your horn.", "Charlie Parker"),
        ("Let's get lost.", "Chet Baker"),
        ("Everybody wants to be a cat.", "The Aristocats"),
        ("Night and day, you are the one.", "Cole Porter"),
    ],
    "featured": [
        ("The special tonight is whatever we just cracked open.", "The house"),
        ("Use it or lose it.", "Every bartender"),
        ("We're featuring this. That's your hint.", "The house"),
        ("If you have a bottle you love, make it the star.", "The house"),
        ("Tonight's push is on the featured bottles. Don't be shy.", "The house"),
        ("The best bottle is the one we need to finish.", "The house"),
        ("Order something with the gold star. That's the assignment.", "The house"),
        ("Waste not, want not — especially the good stuff.", "Proverb"),
        ("Go home with the one that brought you.", "The house"),
        ("If it's on the featured list, it's on us to use it.", "The house"),
    ],
}


# Five Amazon Music search names per theme — mood, not a playlist.
THEME_ARTISTS = {
    "mexican-agave": [
        "Vicente Fernández",
        "Selena",
        "Café Tacvba",
        "Santana",
        "Natalia Lafourcade",
    ],
    "italian-aperitivo": [
        "Paolo Conte",
        "Nino Rota",
        "Mina",
        "Lucio Battisti",
        "Ennio Morricone",
    ],
    "mediterranean": [
        "Cesária Évora",
        "Amália Rodrigues",
        "Ibrahim Maalouf",
        "Pink Martini",
        "Georges Brassens",
    ],
    "asian-spice": [
        "Ryuichi Sakamoto",
        "Joe Hisaishi",
        "Ravi Shankar",
        "Khruangbin",
        "Dengue Fever",
    ],
    "latin-american": [
        "Buena Vista Social Club",
        "Celia Cruz",
        "Caetano Veloso",
        "Mercedes Sosa",
        "Gotan Project",
    ],
    "american-comfort": [
        "Bob Seger",
        "Tom Petty",
        "Creedence Clearwater Revival",
        "Willie Nelson",
        "The Eagles",
    ],
    "classics": [
        "Frank Sinatra",
        "Ella Fitzgerald",
        "Dean Martin",
        "Nat King Cole",
        "Louis Armstrong",
    ],
    "tiki-tropical": [
        "Martin Denny",
        "Arthur Lyman",
        "Les Baxter",
        "Esquivel",
        "Don Ho",
    ],
    "sours": [
        "Stan Getz",
        "Astrud Gilberto",
        "Chet Baker",
        "Blossom Dearie",
        "Julie London",
    ],
    "spirit-forward": [
        "Johnny Cash",
        "Miles Davis",
        "Tom Waits",
        "Leonard Cohen",
        "Howlin' Wolf",
    ],
    "highball": [
        "Phoenix",
        "Air",
        "Vampire Weekend",
        "The Whitest Boy Alive",
        "Daft Punk",
    ],
    "sparkling": [
        "Françoise Hardy",
        "Serge Gainsbourg",
        "Édith Piaf",
        "Pink Martini",
        "Michael Bublé",
    ],
    "garden-herbal": [
        "Nick Drake",
        "Fleet Foxes",
        "Joni Mitchell",
        "Iron & Wine",
        "Bon Iver",
    ],
    "spicy-smoky": [
        "Queens of the Stone Age",
        "The Black Keys",
        "Calexico",
        "Sharon Jones & The Dap-Kings",
        "Jack White",
    ],
    "coffee-dessert": [
        "Sade",
        "Norah Jones",
        "Portishead",
        "Zero 7",
        "Billie Holiday",
    ],
    "bright-citrus": [
        "Antônio Carlos Jobim",
        "Astrud Gilberto",
        "Sérgio Mendes",
        "Bebel Gilberto",
        "Jack Johnson",
    ],
    "bitter": [
        "Nick Cave & The Bad Seeds",
        "Portishead",
        "Massive Attack",
        "Paolo Conte",
        "Tom Waits",
    ],
    "summer-fresh": [
        "The Beach Boys",
        "Jack Johnson",
        "Vampire Weekend",
        "Fleetwood Mac",
        "Daft Punk",
    ],
    "autumn-spice": [
        "Van Morrison",
        "The Band",
        "Neil Young",
        "Fleetwood Mac",
        "Bon Iver",
    ],
    "winter-warm": [
        "Otis Redding",
        "Bill Withers",
        "Ray Charles",
        "The National",
        "Norah Jones",
    ],
    "brunch": [
        "Norah Jones",
        "Feist",
        "Corinne Bailey Rae",
        "Amos Lee",
        "Michael Bublé",
    ],
    "easy": [
        "Jack Johnson",
        "James Taylor",
        "Paul Simon",
        "John Mayer",
        "Amos Lee",
    ],
    "batch-punch": [
        "Earth, Wind & Fire",
        "Stevie Wonder",
        "Chic",
        "Kool & The Gang",
        "ABBA",
    ],
    "low-abv": [
        "Air",
        "Zero 7",
        "Khruangbin",
        "Bonobo",
        "Sade",
    ],
    "jazzy": [
        "Miles Davis",
        "John Coltrane",
        "Billie Holiday",
        "Thelonious Monk",
        "Duke Ellington",
    ],
    "featured": [
        "Prince",
        "David Bowie",
        "Stevie Wonder",
        "Daft Punk",
        "Beyoncé",
    ],
}


def artists_for_theme(slug):
    return list(THEME_ARTISTS.get(slug or "") or [])


def ticker_quotes_for_theme(slug, minimum=100):
    """Ticker payload: themed core first, then a rotated mix of sports, celebrity, and movie lines."""
    from ticker_quotes import CELEBRITY_QUOTES, MOVIE_QUOTES, SPORTS_QUOTES

    themed = list(THEME_QUOTES.get(slug or "") or [])
    seen = {q for q, _ in themed}
    out = list(themed)

    def rotated(seq):
        seq = list(seq)
        if not seq:
            return seq
        n = sum(ord(c) for c in (slug or "")) % len(seq)
        return seq[n:] + seq[:n]

    pools = [
        rotated(SPORTS_QUOTES),
        rotated(CELEBRITY_QUOTES),
        rotated(MOVIE_QUOTES),
    ]
    idxs = [0, 0, 0]
    while len(out) < minimum:
        progressed = False
        for i, pool in enumerate(pools):
            while idxs[i] < len(pool):
                quote, src = pool[idxs[i]]
                idxs[i] += 1
                if quote in seen:
                    continue
                out.append((quote, src))
                seen.add(quote)
                progressed = True
                break
            if len(out) >= minimum:
                break
        if not progressed:
            break
    return [{"quote": q, "movie": src} for q, src in out]


# recipe name → theme slugs (names must match drinks.db)
RECIPE_THEMES = {
    "Absinthe Drip": ["classics", "spirit-forward", "garden-herbal", "mediterranean"],
    "Alabama Slammer": ["american-comfort", "highball", "easy", "bright-citrus"],
    "Amaretto Sour": ["sours", "classics", "american-comfort", "coffee-dessert"],
    "Amaretto Tea": ["coffee-dessert", "winter-warm", "easy"],
    "Americano": ["italian-aperitivo", "classics", "bitter", "highball", "low-abv", "summer-fresh"],
    "Aperol Spritz": ["italian-aperitivo", "classics", "sparkling", "bitter", "summer-fresh", "low-abv", "brunch"],
    "Atlas Martini": ["spirit-forward", "mediterranean", "classics"],
    "Autumn Thunder": ["asian-spice", "tiki-tropical", "highball", "autumn-spice"],
    "Aviation": ["classics", "sours", "garden-herbal"],
    "Avocado Margarita": ["mexican-agave", "latin-american", "sours"],
    "B-52": ["coffee-dessert", "easy"],
    "Bees Knees": ["classics", "sours", "garden-herbal", "easy"],
    "Bellini": ["italian-aperitivo", "sparkling", "brunch", "classics", "low-abv", "easy"],
    "Between the Sheets": ["classics", "sours", "latin-american"],
    "Black Gold": ["coffee-dessert", "winter-warm", "autumn-spice"],
    "Black Velvet": ["sparkling", "classics", "low-abv", "brunch"],
    "Blackjack Redux": ["spicy-smoky", "coffee-dessert", "mexican-agave", "bitter"],
    "Boccie Ball": ["italian-aperitivo", "highball", "easy", "bright-citrus", "low-abv"],
    "Boulevardier": ["american-comfort", "classics", "spirit-forward", "bitter", "autumn-spice"],
    "Breakfast Martini": ["sours", "brunch", "bright-citrus", "classics"],
    "Bushwacker": ["coffee-dessert", "tiki-tropical", "latin-american"],
    "Caesar": ["brunch", "spicy-smoky", "highball", "american-comfort"],
    "Carajillo": ["coffee-dessert", "mexican-agave", "latin-american", "easy", "brunch"],
    "Cocomacoque": ["latin-american", "tiki-tropical", "highball", "batch-punch", "bright-citrus"],
    "Continental": ["classics", "garden-herbal", "sours"],
    "Cosmopolitan": ["classics", "sours", "bright-citrus"],
    "Cumbersome": ["garden-herbal", "mediterranean", "sours", "summer-fresh"],
    "Daiquiri": ["classics", "sours", "latin-american", "tiki-tropical", "summer-fresh"],
    "Dark 'n' Stormy": ["classics", "highball", "spicy-smoky", "asian-spice", "latin-american", "easy", "summer-fresh"],
    "Dirty Martini": ["classics", "spirit-forward", "mediterranean"],
    "Dry Martini": ["classics", "spirit-forward"],
    "Easy Like Sunday Morning": ["highball", "tiki-tropical", "bright-citrus", "easy", "summer-fresh", "batch-punch"],
    "Espresso Martini": ["classics", "coffee-dessert", "brunch", "winter-warm"],
    "Ferrari": ["italian-aperitivo", "spirit-forward", "easy"],
    "Fish House Punch": ["batch-punch", "classics", "american-comfort", "sours"],
    "Flirtini": ["sparkling", "tiki-tropical", "brunch", "bright-citrus"],
    "Flying Dutchman": ["easy", "spirit-forward", "classics"],
    "French 75": ["classics", "sparkling", "sours", "brunch"],
    "French 75 Elderflower": ["sparkling", "garden-herbal", "sours", "brunch", "summer-fresh"],
    "French Connection": ["classics", "spirit-forward", "easy", "winter-warm", "american-comfort"],
    "Frostbite": ["coffee-dessert", "mexican-agave"],
    "Frozen Margarita": ["mexican-agave", "latin-american", "sours", "summer-fresh", "classics"],
    "Gentleman's Agreement": ["coffee-dessert", "spirit-forward", "american-comfort", "autumn-spice"],
    "Gin & Tonic": ["classics", "highball", "garden-herbal", "easy", "summer-fresh", "low-abv", "bright-citrus"],
    "Godfather": ["classics", "spirit-forward", "american-comfort", "easy", "winter-warm"],
    "Godmother": ["easy", "highball", "american-comfort"],
    "Grasshopper": ["classics", "coffee-dessert", "garden-herbal", "winter-warm"],
    "Happy Medium": ["coffee-dessert", "spicy-smoky", "autumn-spice"],
    "Highland Breeze": ["highball", "easy", "bright-citrus", "american-comfort"],
    "Honey Badger": ["asian-spice", "spicy-smoky", "tiki-tropical", "summer-fresh", "sours"],
    "Hot Buttered Rum": ["winter-warm", "classics", "latin-american", "autumn-spice"],
    "Hot Toddy": ["winter-warm", "classics", "american-comfort", "autumn-spice"],
    "Hula Hoop": ["tiki-tropical", "bright-citrus", "summer-fresh"],
    "International Incident": ["coffee-dessert", "easy", "winter-warm"],
    "Irish Coffee": ["coffee-dessert", "winter-warm", "classics", "brunch"],
    "Japanese Highball": ["asian-spice", "highball", "classics", "easy", "low-abv", "summer-fresh"],
    "Japanese Pear": ["asian-spice", "autumn-spice"],
    "Jungle Juice": ["tiki-tropical", "batch-punch", "highball", "latin-american", "summer-fresh"],
    "Kamikaze": ["sours", "classics", "easy", "bright-citrus"],
    "Last Word": ["classics", "sours", "garden-herbal", "spirit-forward"],
    "Limoncello Sunrise": ["mediterranean", "bright-citrus", "brunch", "easy"],
    "Long Island Iced Tea": ["american-comfort", "classics", "highball", "batch-punch"],
    "Lost Lake": ["tiki-tropical", "latin-american", "summer-fresh"],
    "Maiden's Blush": ["sours", "classics", "easy"],
    "Manhattan": ["classics", "spirit-forward", "american-comfort", "autumn-spice", "winter-warm"],
    "Margarita": ["mexican-agave", "latin-american", "classics", "sours", "summer-fresh"],
    "Mezcal Margarita": ["mexican-agave", "latin-american", "sours", "spicy-smoky"],
    "Mimosa": ["sparkling", "brunch", "classics", "bright-citrus", "easy", "low-abv"],
    "Mint Julep": ["american-comfort", "classics", "garden-herbal", "summer-fresh"],
    "Misty Bitch": ["bitter", "italian-aperitivo", "highball", "bright-citrus"],
    "Mojito": ["latin-american", "classics", "garden-herbal", "summer-fresh", "tiki-tropical", "highball"],
    "Morning Glory": ["sparkling", "brunch", "bright-citrus", "easy"],
    "Moscow Mule": ["classics", "highball", "asian-spice", "spicy-smoky", "easy", "summer-fresh"],
    "Mudslide": ["coffee-dessert", "easy", "winter-warm"],
    "Mulled Claret": ["winter-warm", "autumn-spice", "batch-punch", "classics"],
    "Negroni": ["italian-aperitivo", "classics", "bitter", "spirit-forward"],
    "Negroni Sbagliato": ["italian-aperitivo", "classics", "sparkling", "bitter", "low-abv"],
    "New York Sour": ["classics", "sours", "american-comfort"],
    "Nightmare": ["classics", "spirit-forward"],
    "Nutty Irishman": ["coffee-dessert", "winter-warm", "easy"],
    "Oaxacan Old Fashioned": ["mexican-agave", "latin-american", "spirit-forward", "spicy-smoky", "classics"],
    "Old Fashioned": ["classics", "spirit-forward", "american-comfort", "autumn-spice", "winter-warm"],
    "Ouzo Lemonade": ["mediterranean", "highball", "easy", "summer-fresh", "bright-citrus", "low-abv", "garden-herbal"],
    "Painkiller": ["tiki-tropical", "latin-american", "classics", "summer-fresh"],
    "Paloma": ["mexican-agave", "latin-american", "classics", "highball", "bright-citrus", "easy", "summer-fresh"],
    "Paper Plane": ["american-comfort", "sours", "bitter", "classics", "autumn-spice"],
    "Pimm's Cup": ["garden-herbal", "summer-fresh", "highball", "low-abv", "batch-punch", "easy"],
    "Pimm's Spritz": ["garden-herbal", "sparkling", "summer-fresh", "low-abv"],
    "Pimm's Sundowner": ["easy", "bright-citrus", "summer-fresh", "low-abv"],
    "Pineapple Daiquiri": ["sours", "tiki-tropical", "latin-american"],
    "Piña Colada": ["tiki-tropical", "latin-american", "classics", "summer-fresh", "batch-punch"],
    "Quaalude": ["coffee-dessert", "easy"],
    "Red Death": ["american-comfort", "bright-citrus", "easy"],
    "Repossession": ["mexican-agave", "sours", "latin-american"],
    "Rob Roy": ["classics", "spirit-forward", "autumn-spice", "winter-warm"],
    "Royal Bermuda Yacht Club": ["tiki-tropical", "classics", "sours", "latin-american"],
    "Rum Old Fashioned": ["spirit-forward", "latin-american", "classics", "autumn-spice"],
    "Rum and Coke": ["classics", "highball", "easy", "latin-american", "american-comfort", "summer-fresh"],
    "Russian Coffee": ["coffee-dessert", "winter-warm"],
    "Sazerac": ["classics", "spirit-forward", "american-comfort", "autumn-spice", "winter-warm"],
    "Scofflaw": ["classics", "sours", "american-comfort", "spirit-forward"],
    "Screwdriver": ["classics", "brunch", "easy", "bright-citrus", "highball", "american-comfort"],
    "Sex on the Beach": ["classics", "highball", "bright-citrus", "easy", "summer-fresh"],
    "Siberian Sleighride": ["coffee-dessert", "winter-warm"],
    "Singapore Sling": ["classics", "tiki-tropical", "sours", "highball", "asian-spice"],
    "Sit Back and Relax": ["garden-herbal", "highball", "summer-fresh", "american-comfort"],
    "Smoking Banana": ["spicy-smoky", "mexican-agave", "spirit-forward", "latin-american"],
    "Snow Bunny": ["winter-warm", "coffee-dessert", "easy", "autumn-spice"],
    "Socrates": ["spirit-forward", "autumn-spice"],
    "Southern Belle": ["italian-aperitivo", "sours", "bitter"],
    "Southern Shag": ["american-comfort", "easy", "highball", "bright-citrus", "summer-fresh"],
    "Spanish Coffee": ["coffee-dessert", "winter-warm", "mediterranean"],
    "Sparkling Limoncello Lemonade": ["sparkling", "mediterranean", "summer-fresh", "bright-citrus", "low-abv", "easy", "brunch", "garden-herbal"],
    "Split Decisions": ["coffee-dessert", "tiki-tropical"],
    "Stiletto": ["sours", "american-comfort", "easy"],
    "Tequila Sunrise": ["mexican-agave", "latin-american", "brunch", "easy", "bright-citrus", "highball", "classics"],
    "The Gardener": ["garden-herbal", "mexican-agave", "spicy-smoky", "summer-fresh"],
    "Tom Collins": ["classics", "sours", "highball", "summer-fresh", "easy", "bright-citrus"],
    "Virgin Mojito": ["garden-herbal", "summer-fresh", "low-abv", "easy", "latin-american"],
    "Vieux Carré": ["classics", "spirit-forward", "american-comfort", "autumn-spice", "winter-warm"],
    "Vodka Soda": ["easy", "highball", "low-abv", "summer-fresh", "bright-citrus"],
    "W Bar Saketini": ["asian-spice", "sours"],
    "Whiskey Sour": ["classics", "sours", "american-comfort"],
    "White Russian": ["classics", "coffee-dessert", "easy", "winter-warm"],
    "White Spider": ["sours", "classics"],
    "Will Rogers": ["classics", "bright-citrus"],
    "Zombie": ["tiki-tropical", "latin-american", "classics", "batch-punch", "summer-fresh"],
}

# Jazz-club / speakeasy night — stirred, New Orleans, a little sparkle.
for _name in (
    "Absinthe Drip",
    "Amaretto Sour",
    "Atlas Martini",
    "Aviation",
    "Bees Knees",
    "Between the Sheets",
    "Black Velvet",
    "Boulevardier",
    "Carajillo",
    "Continental",
    "Dirty Martini",
    "Dry Martini",
    "Espresso Martini",
    "Ferrari",
    "Flying Dutchman",
    "French 75",
    "French 75 Elderflower",
    "French Connection",
    "Gentleman's Agreement",
    "Godfather",
    "Grasshopper",
    "Irish Coffee",
    "Last Word",
    "Maiden's Blush",
    "Manhattan",
    "Mint Julep",
    "Negroni",
    "Negroni Sbagliato",
    "New York Sour",
    "Nightmare",
    "Oaxacan Old Fashioned",
    "Old Fashioned",
    "Paper Plane",
    "Rob Roy",
    "Rum Old Fashioned",
    "Sazerac",
    "Scofflaw",
    "Socrates",
    "Spanish Coffee",
    "Stiletto",
    "Tom Collins",
    "Vieux Carré",
    "Whiskey Sour",
    "White Spider",
    "Will Rogers",
):
    RECIPE_THEMES[_name] = list(RECIPE_THEMES[_name]) + ["jazzy"]



def themes_by_family():
    families = []
    for fam in THEME_FAMILIES:
        items = [t for t in THEMES if t[2] == fam["key"]]
        families.append({**fam, "themes": items})
    return families
