"""Extra ticker lines (sports + celebrity). Movie quotes stay seeded in app.py."""

# Amusing sports quotes — attribution goes in the ticker's "movie" slot.
SPORTS_QUOTES = [
    ("It ain't over till it's over.", "Yogi Berra"),
    ("It's like déjà vu all over again.", "Yogi Berra"),
    ("When you come to a fork in the road, take it.", "Yogi Berra"),
    ("You can observe a lot by watching.", "Yogi Berra"),
    ("Nobody goes there anymore. It's too crowded.", "Yogi Berra"),
    ("The future ain't what it used to be.", "Yogi Berra"),
    ("I never said most of the things I said.", "Yogi Berra"),
    ("Baseball is ninety percent mental. The other half is physical.", "Yogi Berra"),
    ("If the world were perfect, it wouldn't be.", "Yogi Berra"),
    ("We made too many wrong mistakes.", "Yogi Berra"),
    ("It gets late early out here.", "Yogi Berra"),
    ("If you don't know where you are going, you might wind up someplace else.", "Yogi Berra"),
    ("Always go to other people's funerals, otherwise they won't come to yours.", "Yogi Berra"),
    ("The secret of managing is to keep the guys who hate you away from the guys who are undecided.", "Casey Stengel"),
    ("Good pitching will always stop good hitting, and vice versa.", "Casey Stengel"),
    ("There comes a time in every man's life, and I've had plenty of them.", "Casey Stengel"),
    ("Never make predictions, especially about the future.", "Casey Stengel"),
    ("Don't look back. Something might be gaining on you.", "Satchel Paige"),
    ("Age is a question of mind over matter. If you don't mind, it doesn't matter.", "Satchel Paige"),
    ("How old would you be if you didn't know how old you are?", "Satchel Paige"),
    ("I don't know. I never smoked Astroturf.", "Tug McGraw"),
    ("I knew when my career was over. In 1965 my baseball card came out with no picture.", "Bob Uecker"),
    ("The way to catch a knuckleball is to wait until it stops rolling and then pick it up.", "Bob Uecker"),
    ("Sporting goods companies pay me not to endorse their products.", "Bob Uecker"),
    ("I'd rather be lucky than good.", "Lefty Gomez"),
    ("My goals are to hit .300, score 100 runs, and stay injury-prone.", "Mickey Rivers"),
    ("We'll do all right if we can capitalize on our mistakes.", "Mickey Rivers"),
    ("I have seen the future, and it is much like the present, only longer.", "Dan Quisenberry"),
    ("I ain't an athlete, lady. I'm a baseball player.", "John Kruk"),
    ("There is one word in America that says it all, and that one word is, 'You never know.'", "Joaquín Andújar"),
    ("He slides into second with a stand-up double.", "Jerry Coleman"),
    ("Solo homers usually come with no one on base.", "Ralph Kiner"),
    ("If Casey Stengel were alive today, he'd be spinning in his grave.", "Ralph Kiner"),
    ("He slud into third.", "Dizzy Dean"),
    ("It ain't braggin' if you can back it up.", "Dizzy Dean"),
    ("The doctors x-rayed my head and found nothing.", "Dizzy Dean"),
    ("I went through life as a player to be named later.", "Joe Garagiola"),
    ("When we win, I eat a lot. When we lose, I eat a lot. When we're rained out, I eat a lot.", "Tommy Lasorda"),
    ("Me carrying a briefcase is like a hotdog wearing earrings.", "Sparky Anderson"),
    ("This ain't a football game. We do this every day.", "Earl Weaver"),
    ("Nice guys finish last.", "Leo Durocher"),
    ("I never questioned the integrity of an umpire. Their eyesight, yes.", "Leo Durocher"),
    ("I will never have a heart attack. I give them.", "George Steinbrenner"),
    ("Fans don't boo nobodies.", "Reggie Jackson"),
    ("It took me seventeen years to get three thousand hits in baseball. I did it in one afternoon on the golf course.", "Hank Aaron"),
    ("Don't worry about the horse being blind, just load the wagon.", "John Madden"),
    ("There's two kinds of coaches: them that's fired and them that's gonna be fired.", "Bum Phillips"),
    ("He can take his'n and beat your'n, and take your'n and beat his'n.", "Bum Phillips"),
    ("Asked about his team's execution: I'm in favor of it.", "John McKay"),
    ("We didn't tackle well today, but we made up for it by not blocking.", "John McKay"),
    ("Playoffs? Don't talk about—playoffs?", "Jim Mora"),
    ("You play to win the game!", "Herm Edwards"),
    ("I guarantee it.", "Joe Namath"),
    ("I can't wait until tomorrow, because I get better looking every day.", "Joe Namath"),
    ("Ninety percent I'll spend on whiskey, women, and the good life. The other ten I'll probably waste.", "Ken Stabler"),
    ("I never lost a game. I just ran out of time.", "Bobby Layne"),
    ("A genius is a guy like Norman Einstein.", "Joe Theismann"),
    ("If it's the ultimate game, how come they're playing it again next year?", "Duane Thomas"),
    ("I'm just here so I won't get fined.", "Marshawn Lynch"),
    ("Everybody has a plan until they get punched in the mouth.", "Mike Tyson"),
    ("I'm so fast that last night I turned off the light switch and was in bed before the room was dark.", "Muhammad Ali"),
    ("It's hard to be humble when you're as great as I am.", "Muhammad Ali"),
    ("I want to keep fighting because it is the only thing that keeps me out of the hamburger joints.", "George Foreman"),
    ("I've won at every level, except college and pro.", "Shaquille O'Neal"),
    ("Practice? We talkin' about practice?", "Allen Iverson"),
    ("We're going to turn this team around 360 degrees.", "Jason Kidd"),
    ("My sister's expecting a baby, and I don't know if I'm going to be an uncle or an aunt.", "Chuck Nevitt"),
    ("The only difference between a good shot and a bad shot is if it goes in or not.", "Charles Barkley"),
    ("You cannot be serious!", "John McEnroe"),
    ("Whoever said 'It's not whether you win or lose that counts' probably lost.", "Martina Navratilova"),
    ("If you are caught on a golf course during a storm and are afraid of lightning, hold up a 1-iron. Not even God can hit a 1-iron.", "Lee Trevino"),
    ("The older I get, the better I used to be.", "Lee Trevino"),
    ("Golf is a game invented by the same people who think music comes out of a bagpipe.", "Lee Trevino"),
    ("I asked my caddie for a sand wedge and he came back ten minutes later with a ham on rye.", "Chi-Chi Rodríguez"),
    ("I'm playing like Tarzan and scoring like Jane.", "Chi-Chi Rodríguez"),
    ("If you are going to throw a club, throw it ahead of you so you don't waste energy going back to pick it up.", "Tommy Bolt"),
    ("Some people think football is a matter of life and death. I can assure you it is much more serious than that.", "Bill Shankly"),
    ("I wouldn't say I was the best manager in the business. But I was in the top one.", "Brian Clough"),
    ("If God had wanted us to play football in the clouds, he'd have put grass up there.", "Brian Clough"),
    ("Please don't call me arrogant, but I'm European champion and I think I'm a special one.", "José Mourinho"),
    ("When the seagulls follow the trawler, it is because they think sardines will be thrown into the sea.", "Eric Cantona"),
    ("I couldn't settle in Italy—it was like living in a foreign country.", "Ian Rush"),
    ("I spent a lot of money on booze, birds and fast cars. The rest I just squandered.", "George Best"),
    ("Football is a simple game. Twenty-two men chase a ball for 90 minutes and at the end, the Germans always win.", "Gary Lineker"),
    ("You can't win anything with kids.", "Alan Hansen"),
    ("I never make predictions, and I never will.", "Paul Gascoigne"),
    ("Unless I'm very much mistaken… I am very much mistaken!", "Murray Walker"),
    ("There's nothing wrong with the car except that it's on fire.", "Murray Walker"),
    ("Last season we couldn't win at home and we were losing on the road. I couldn't think of anyplace else to play.", "Harry Neale"),
    ("The three important elements of hockey are: forecheck, backcheck, and paycheck.", "Harry Neale"),
    ("How would you like a job where every time you make a mistake, a big red light goes on and 18,000 people boo?", "Jacques Plante"),
    ("I think the world is run by C students.", "Al McGuire"),
    ("The only mystery in life is why kamikaze pilots wore helmets.", "Al McGuire"),
    ("I asked him, 'Son, is it ignorance or apathy?' He said, 'Coach, I don't know and I don't care.'", "Frank Layden"),
    ("We have a great bunch of outside shooters. Unfortunately, all our games are played indoors.", "Frank Layden"),
    ("The trouble with officials is they just don't care who wins.", "Abe Lemons"),
    ("I don't need a timeout. I know what's going on. I just don't know what to do about it.", "Doug Moe"),
    ("Some people are born on third base and go through life thinking they hit a triple.", "Barry Switzer"),
    ("I've had more clubs than Jack Nicklaus.", "Tommy Docherty"),
    ("He's about as predictable as a wasp on speed.", "Sid Waddell"),
]

# Funny celebrity quotes — same ticker pool, same attribution slot.
CELEBRITY_QUOTES = [
    ("I can resist everything except temptation.", "Oscar Wilde"),
    ("I have the simplest tastes. I am always satisfied with the best.", "Oscar Wilde"),
    ("Work is the curse of the drinking classes.", "Oscar Wilde"),
    ("The reports of my death are greatly exaggerated.", "Mark Twain"),
    ("Never put off till tomorrow what you can do the day after tomorrow just as well.", "Mark Twain"),
    ("I don't want to belong to any club that would accept me as a member.", "Groucho Marx"),
    ("Those are my principles, and if you don't like them… well, I have others.", "Groucho Marx"),
    ("Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.", "Groucho Marx"),
    ("I cook with wine. Sometimes I even add it to the food.", "W. C. Fields"),
    ("A woman drove me to drink, and I didn't even have the decency to thank her.", "W. C. Fields"),
    ("Everybody's got to believe in something. I believe I'll have another drink.", "W. C. Fields"),
    ("When I'm good, I'm very good. But when I'm bad, I'm better.", "Mae West"),
    ("I used to be Snow White, but I drifted.", "Mae West"),
    ("I'd rather have a bottle in front of me than a frontal lobotomy.", "Dorothy Parker"),
    ("If you haven't got anything nice to say about anybody, come sit next to me.", "Dorothy Parker"),
    ("This is not a novel to be tossed aside lightly. It should be thrown with great force.", "Dorothy Parker"),
    ("I intend to live forever. So far, so good.", "Steven Wright"),
    ("I spilled spot remover on my dog. Now he's gone.", "Steven Wright"),
    ("I went to a restaurant that serves breakfast at any time. So I ordered French toast during the Renaissance.", "Steven Wright"),
    ("An escalator can never break. It can only become stairs.", "Mitch Hedberg"),
    ("Rice is great if you're really hungry and want to eat two thousand of something.", "Mitch Hedberg"),
    ("A day without sunshine is like, you know, night.", "Steve Martin"),
    ("I don't want to achieve immortality through my work. I want to achieve it through not dying.", "Woody Allen"),
    ("I'm not offended by dumb blonde jokes because I know I'm not dumb… and I'm not blonde.", "Dolly Parton"),
    ("It costs a lot of money to look this cheap.", "Dolly Parton"),
    ("If you obey all the rules, you miss all the fun.", "Katharine Hepburn"),
    ("Old age ain't no place for sissies.", "Bette Davis"),
    ("I knew I was an unwanted baby when I saw that my bath toys were a toaster and a radio.", "Joan Rivers"),
    ("Housework can't kill you, but why take a chance?", "Phyllis Diller"),
    ("Insanity is hereditary. You can get it from your children.", "Erma Bombeck"),
    ("Everything is funny as long as it is happening to somebody else.", "Will Rogers"),
    ("You know you're getting old when the candles cost more than the cake.", "Bob Hope"),
    ("I don't feel old. I don't feel anything until noon. Then it's time for my nap.", "Bob Hope"),
    ("If life were fair, Elvis would be alive and all the impersonators would be dead.", "Johnny Carson"),
    ("The secret of staying young is to live honestly, eat slowly, and lie about your age.", "Lucille Ball"),
    ("I love deadlines. I love the whooshing noise they make as they go by.", "Douglas Adams"),
    ("In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.", "Douglas Adams"),
    ("Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.", "Terry Pratchett"),
    ("You're not drunk if you can lie on the floor without holding on.", "Dean Martin"),
    ("I feel sorry for people who don't drink. When they wake up in the morning, that's as good as they're going to feel all day.", "Dean Martin"),
    ("The whole world is about three drinks behind.", "Humphrey Bogart"),
    ("I had the right to remain silent, but I didn't have the ability.", "Ron White"),
    ("If life gives you lemons, find somebody whose life has given them vodka, and have a party.", "Ron White"),
    ("A two-year-old is kind of like having a blender, but you don't have a top for it.", "Jerry Seinfeld"),
    ("It's amazing that the amount of news that happens in the world every day always just exactly fits the newspaper.", "Jerry Seinfeld"),
    ("I don't need you to remind me of my age. I have a bladder to do that for me.", "Stephen Fry"),
    ("I have learned from my mistakes, and I am sure I can repeat them exactly.", "Peter Cook"),
    ("Money can't buy you happiness, but it does bring you a more pleasant form of misery.", "Spike Milligan"),
    ("With my sunglasses on, I'm Jack Nicholson. Without them, I'm fat and 60.", "Jack Nicholson"),
    ("Behind every great man is a woman rolling her eyes.", "Jim Carrey"),
]


MOVIE_QUOTES = [
    ("I'll be back.", 'The Terminator'),
    ('May the Force be with you.', 'Star Wars'),
    ("Here's looking at you, kid.", 'Casablanca'),
    ('You talking to me?', 'Taxi Driver'),
    ("I'll have what she's having.", 'When Harry Met Sally'),
    ("We're gonna need a bigger boat.", 'Jaws'),
    ('Life is like a box of chocolates.', 'Forrest Gump'),
    ("You can't handle the truth!", 'A Few Good Men'),
    ('I feel the need—the need for speed.', 'Top Gun'),
    ('Nobody puts Baby in a corner.', 'Dirty Dancing'),
    ("That'll do, pig. That'll do.", 'Babe'),
    ("I am serious. And don't call me Shirley.", 'Airplane!'),
    ("It's just a flesh wound.", 'Monty Python and the Holy Grail'),
    ('Strange women lying in ponds distributing swords is no basis for a system of government.', 'Monty Python and the Holy Grail'),
    ('Inconceivable!', 'The Princess Bride'),
    ('Hello. My name is Inigo Montoya. You killed my father. Prepare to die.', 'The Princess Bride'),
    ('Have fun storming the castle!', 'The Princess Bride'),
    ('As you wish.', 'The Princess Bride'),
    ('Why so serious?', 'The Dark Knight'),
    ('I am Groot.', 'Guardians of the Galaxy'),
    ('I volunteer as tribute!', 'The Hunger Games'),
    ('Winter is coming.', 'Game of Thrones'),
    ('This is the way.', 'The Mandalorian'),
    ('Just keep swimming.', 'Finding Nemo'),
    ('To infinity and beyond!', 'Toy Story'),
    ("There's no place like home.", 'The Wizard of Oz'),
    ("Toto, I've a feeling we're not in Kansas anymore.", 'The Wizard of Oz'),
    ("I'm king of the world!", 'Titanic'),
    ('Houston, we have a problem.', 'Apollo 13'),
    ('Show me the money!', 'Jerry Maguire'),
    ('You had me at hello.', 'Jerry Maguire'),
    ('I see dead people.', 'The Sixth Sense'),
    ("They may take our lives, but they'll never take our freedom!", 'Braveheart'),
    ('Say hello to my little friend!', 'Scarface'),
    ('Keep your friends close, but your enemies closer.', 'The Godfather Part II'),
    ("I'm going to make him an offer he can't refuse.", 'The Godfather'),
    ('Leave the gun. Take the cannoli.', 'The Godfather'),
    ("What we've got here is failure to communicate.", 'Cool Hand Luke'),
    ('Go ahead, make my day.', 'Sudden Impact'),
    ('Do I feel lucky? Well, do ya, punk?', 'Dirty Harry'),
    ('Yippee-ki-yay.', 'Die Hard'),
    ('Welcome to the party, pal.', 'Die Hard'),
    ('I love the smell of napalm in the morning.', 'Apocalypse Now'),
    ('The first rule of Fight Club is: you do not talk about Fight Club.', 'Fight Club'),
    ("Gentlemen, you can't fight in here! This is the War Room!", 'Dr. Strangelove'),
    ("Roads? Where we're going, we don't need roads.", 'Back to the Future'),
    ('Great Scott!', 'Back to the Future'),
    ('If you build it, he will come.', 'Field of Dreams'),
    ("There's no crying in baseball!", 'A League of Their Own'),
    ("You're gonna need a bigger closet.", 'Clueless'),
    ('On Wednesdays we wear pink.', 'Mean Girls'),
    ("She doesn't even go here!", 'Mean Girls'),
    ('Stop trying to make fetch happen.', 'Mean Girls'),
    ('That is so fetch.', 'Mean Girls'),
    ("I'm not bad. I'm just drawn that way.", 'Who Framed Roger Rabbit'),
    ("I'm walking here! I'm walking here!", 'Midnight Cowboy'),
    ('What is this, a center for ants?', 'Zoolander'),
    ('Moisture is the essence of wetness, and wetness is the essence of beauty.', 'Zoolander'),
    ('I feel pretty, oh so pretty.', 'West Side Story'),
    ("It's not a tumor!", 'Kindergarten Cop'),
    ('Get to the chopper!', 'Predator'),
    ('If it bleeds, we can kill it.', 'Predator'),
    ('Come with me if you want to live.', 'Terminator 2'),
    ('Hasta la vista, baby.', 'Terminator 2'),
    ('I know kung fu.', 'The Matrix'),
    ('There is no spoon.', 'The Matrix'),
    ("Why didn't you put the bunny back in the box?", 'Con Air'),
    ("It's a trap!", 'Return of the Jedi'),
    ('Do. Or do not. There is no try.', 'The Empire Strikes Back'),
    ('I find your lack of faith disturbing.', 'Star Wars'),
    ("These aren't the droids you're looking for.", 'Star Wars'),
    ('I am your father.', 'The Empire Strikes Back'),
    ('Never tell me the odds.', 'The Empire Strikes Back'),
    ("That's no moon. It's a space station.", 'Star Wars'),
    ("I've got a good feeling about this.", 'Solo: A Star Wars Story'),
    ('I have a bad feeling about this.', 'Star Wars'),
    ("The name's Bond. James Bond.", 'Dr. No'),
    ('Shaken, not stirred.', 'Goldfinger'),
    ('A martini. Shaken, not stirred.', 'Goldfinger'),
    ('Bond. James Bond.', 'Dr. No'),
    ("I'm the king of the world!", 'Titanic'),
    ('You complete me.', 'Jerry Maguire'),
    ('After all, tomorrow is another day!', 'Gone with the Wind'),
    ("Frankly, my dear, I don't give a damn.", 'Gone with the Wind'),
    ("I'm as mad as hell, and I'm not going to take this anymore!", 'Network'),
    ("You can't sit with us!", 'Mean Girls'),
    ("So you're telling me there's a chance.", 'Dumb and Dumber'),
    ("We got no food, we got no jobs… our pets' heads are falling off!", 'Dumb and Dumber'),
    ('Just when I thought I was out, they pull me back in.', 'The Godfather Part III'),
    ("I'm not even supposed to be here today!", 'Clerks'),
    ('Party on, Wayne. Party on, Garth.', "Wayne's World"),
    ('Schwing!', "Wayne's World"),
    ("We're not worthy!", "Wayne's World"),
    ('Bueller? Bueller?', "Ferris Bueller's Day Off"),
    ("Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", "Ferris Bueller's Day Off"),
    ('Carpe diem. Seize the day, boys.', 'Dead Poets Society'),
    ("I'm the dude. So that's what you call me.", 'The Big Lebowski'),
    ('The Dude abides.', 'The Big Lebowski'),
    ('This is what happens when you find a stranger in the Alps!', 'The Big Lebowski'),
    ("Yeah, well, you know, that's just like, your opinion, man.", 'The Big Lebowski'),
    ('I drink your milkshake!', 'There Will Be Blood'),
    ('I am the one who knocks.', 'Breaking Bad'),
    ('Say my name.', 'Breaking Bad'),
    ("They're taking the hobbits to Isengard!", 'The Lord of the Rings'),
    ('My precious.', 'The Lord of the Rings'),
    ('You shall not pass!', 'The Lord of the Rings'),
    ('Even the smallest person can change the course of the future.', 'The Lord of the Rings'),
    ('One does not simply walk into Mordor.', 'The Lord of the Rings'),
    ("It's only a wafer-thin mint.", "Monty Python's The Meaning of Life"),
    ('This parrot is no more! It has ceased to be!', "Monty Python's Flying Circus"),
    ("I'm not a smart man, but I know what love is.", 'Forrest Gump'),
    ('Run, Forrest, run!', 'Forrest Gump'),
    ('Mama always said dying was a part of life.', 'Forrest Gump'),
    ('Wilsoooon!', 'Cast Away'),
    ('I wish I knew how to quit you.', 'Brokeback Mountain'),
    ("I'm just one stomach flu away from my goal weight.", 'The Devil Wears Prada'),
    ("That's what I do. I drink, and I know things.", 'Game of Thrones'),
    ('Hold the door.', 'Game of Thrones'),
    ('I solemnly swear that I am up to no good.', 'Harry Potter'),
    ("You're a wizard, Harry.", 'Harry Potter'),
    ('After all this time? Always.', 'Harry Potter'),
    ('Why is the rum gone?', 'Pirates of the Caribbean'),
    ('This is the day you will always remember as the day you almost caught Captain Jack Sparrow.', 'Pirates of the Caribbean'),
    ("The code is more what you'd call guidelines than actual rules.", 'Pirates of the Caribbean'),
    ('Savvy?', 'Pirates of the Caribbean'),
]

def extra_ticker_quotes():
    return list(SPORTS_QUOTES) + list(CELEBRITY_QUOTES)
